### PR TITLE
allowing import and export, fixing issue with Webpack

### PR DESCRIPTION
**Pull request by Krisa**
This is a fix for https://github.com/olov/ng-annotate/issues/227 and _might_ help partially that: https://github.com/olov/ng-annotate/issues/237

### CODE REVIEW

**Comment by Krisa** [comment]
I'm using it in our development since my pull request, and it works as long as you're mindful, but it's clearly a bit fragile and there are cases which not work. Among others:
 - `export default angular.module(...).config(function("$willNotGetAnnotated"){})` will fail being annotated. But moving the function outside solves the issue.

- there is no "automatic" annotation, so that when using a function/class in a standalone module (file), it will obviously be ignored by the current logic. A manual @ngInject is necessary.

- "ngInject", depending on the situation, does not work. /*@ngInject*/ will, as far as I have seen so far, always work.

**Comment by vperron** [comment]
Albeit being fragile, at least we'll be able to get minimal import/export support in ng-annotate. I guess improving it to make it 100% functional will follow. Every little effort helps. Right now I don't have time to do this, but with that merged at least I won't change my toolchain :)

**Comment by olov** [comment]
https://github.com/olov/ng-annotate/issues/245

**Comment by olov** [comment]
#245

**Pull request closed without merging**
