### PR TITLE
Fix inconsistency between `map` and `sourcemap`

### PR DESCRIPTION
**Pull request by smrq**

### CODE REVIEW

**Comment by mzgol** [comment]
It still doesn't work for me. Could you checkout my `grunt-ng-annotate`'s WIP branch [combine-sourcemap](https://github.com/mzgol/grunt-ng-annotate/tree/combine-sourcemaps), run `npm install`, swap `ng-annotate` in `node_modules` to your version and then `npm test`? You'll see that:
1. Both non-combined map tests fail, only the combined one passes.
2. If you revert just the changes to `tasks/ng-annotate.js` from the last commit on the `combine-sourcemap` branch (it's just `sourcemap -> map` renaming) the combined tests fail & the individual source map ones succeed.

Let me know if you need help with getting it running.

**Comment by mzgol** [comment]
Ahh, I'm sorry, I tested on the wrong branch. <badum, psst> It seems to work fine. :) Tests for this whole behavior would be useful (I've just added them to `grunt-ng-annotate` but it seems they should be here) but it's better to have it working than broken anyway.

@olov could you merge?

**Comment by omsmith** [comment]
Great, I'll have to investigate and see if this clears up https://github.com/substack/node-browserify/issues/1192

**Comment by mzgol** [comment]
Ah, one thing - the generated path seems wrong unless I broke sth. You can try on my [combine-sourcemap](https://github.com/mzgol/grunt-ng-annotate/tree/combine-sourcemaps) branch I mentioned before. I'm transforming `test/fixtures/not-annotated-es6.js` via babel to `test/tmp/not-annotated-es6.js` and then pass it via `grunt-ng-annotate` & generate `test/tmp/not-annotated-es6-source-map.js`. The map file's sources is `['not-annotated-es6.js']` so it points to the second file instead of the first.

**Comment by smrq** [comment]
Are you totally sure your test is correct?  Did the parameter you are passing in as `inFile` exactly match babel's output in `sources`?  That's how the sourcemap combination algorithm works (for more info than you can shake a stick at, see: [mozilla/source-map](https://github.com/mozilla/source-map)).

Because of the possibility of misconfiguration, I just updated the code to ignore inFile when there is an incoming sourcemap with the `file` property specified.  That should wire up the combination step correctly at all times.

**Comment by smrq** [comment]
Also done the same for sourceRoot, for the same reason.

**Comment by mzgol** [comment]
> Are you totally sure your test is correct? Did the parameter you are passing in as inFile exactly match babel's output in sources?

It didn't. babel returns the map with `sources: [ 'test/fixtures/not-annotated-es6.js' ]`; this was relative to the main project directory so I added `sourceRoot: '/Users/mgol/Documents/projects/public/mine/grunt-ng-annotate'`. The `inFile` that I'm passing is just `not-annotated-es6.js` since both source & destination files are in the same directory.

I'm not sure how to do it all differently without reading the incoming source map if it exists. IMO it shouldn't matter - I'm just providing an input file and the source map generating algorithm should itself look further.

In any case, your newest version of the patch passes my tests so it should be OK. :+1:

**Comment by smrq** [comment]
Awesome, glad it works for you now!  The internals of sourcemaps are just so obnoxiously fiddly.

@olov - Should be good to merge, I think.

**Pull request merged**
