### PR TITLE
add travis

### LINKED ISSUE #129: Continuous integration
Did you think about running automated tests on Travis (for UNIX) and AppVeyor (for Windows)? Or do you have any other CI setup enabled that's just not published in the repository?

### PR DESCRIPTION
**Pull request by mastilver**
Hi

I just added a travis.yml and the build badge
Before merging, you just need to log in travis-ci.com and 
enable this repo

closes #129

### CODE REVIEW

**Comment by olov** [comment]
Thanks, now it's up and running. A weird thing is that some of the older node-versions didn't manage to build properly, for example node 0.12.9. I've removed them from .travis.yml for now, because the errors were very undeterministic and hard to track down. Almost to the point that I'm suspecting it to be related with some older v8-bugs, although I know that it should probably not be the case. cc @mzgol

**Comment by mzgol** [comment]
0.11 are pre-releases to 0.12, it doesn't make sense to test on the latest 0.11 Otherwise you should test on earlier 0.11s as well, after all they all introduced breaking changes so if someone doesn't update from 0.11.13 to 0.12 then someone else doesn't update from 0.11.12 to 0.11.13.

I wouldn't test on 0.6 but whatever you want.

**Comment by olov** [comment]
@mzgol check out https://github.com/olov/ng-annotate/blob/master/.travis.yml - I've only enabled 0.10 of the pre 1.0 releases. I'm still puzzled why 0.12 is problematic but I'm leaving that for now because there are so many other things to do (such as releasing ng-annotate 1.1)

**Comment by mzgol** [comment]
BTW, this might be useful to determine the testing strategy: https://docs.google.com/spreadsheets/d/1AY1GbB1WGix4CZXY6L-6QEFZlArN1C_Ew3jMMWQ1XpQ/htmlview#gid=0&vpid=A2

npm stats showing popularity of various Node/iojs version. tl;dr: no one uses Node<0.10, almost no one uses iojs. In other words, almost no one uses unsupported versions which is good!

**Comment by mzgol** [comment]
As for versions 4 & 5, only latest 4.x.y & 5.x.y are supported by upstream. 4.2.y is the current latest LTS.

**Comment by olov** [comment]
@mzgol thanks, that's useful!

**Pull request merged**
